models:
  - id: model1
    endpoint: http://localhost:8000
    max_requests_per_second: 10
    weight: 0.7
  - id: model2
    endpoint: http://localhost:8001
    max_requests_per_second: 10
    weight: 0.3